### ISSUE TITLE
Error on Launch for Family Share Games.

### ISSUE THREAD

**Issue by Boii1** [linkthehylian/GreenLuma-Reborn-App#10]
Dark Souls 3 just updated yesterday to remove Family Share so someone recommended me this. This in fact removed the Purchase option and replaced it with Play tricking Steam I would assume. However upon launching it, the error:

"Steam Error"
"Application load error 6:0000065432"

Shows up making the program unable to be launched. Is there a way to fix this or is it an issue with the game or client? I can confirm it launches perfectly fine on main Steam account but it fails to launch on the injected client. I am using 2020 1.0.9 and AppList 0.txt 374320

**Comment by linkthehylian** [comment]
This is not a question for me. It's for Steam006. View his GL2020 thread [here](https://cs.rin.ru/forum/viewtopic.php?f=29&t=103709).
