### ISSUE TITLE
Arma 3 is not working with green luma 2020

### ISSUE THREAD

**Issue by Szymo1337** [linkthehylian/GreenLuma-Reborn-App#11]
I just would like to add it to the blacklist because it probably has some issues with battleye. We tried it with 4 of my friends didnt work for single one of them.
They all recieved this error that i attached to the post. I dont know if there is an solution. But i just want to give feedback
https://imgur.com/a/Wbm0Pss

**Comment by linkthehylian** [comment]
The Blacklist is only for games that you **receive a game ban** on for trying to use GreenLuma. A simple error like that is worth noting, but not something worth adding to the list.

Regardless, thanks for your input. :)
