### ISSUE TITLE
some games not loading

### ISSUE THREAD

**Issue by peteandrewd** [linkthehylian/GreenLuma-Reborn-App#3]
Some games crash on bootup and exits out to main screen.
Why/how to fix?

**Comment by linkthehylian** [comment]
Explained [here](https://github.com/linkthehylian/GreenLuma-Reborn-App#can-i-get-banned-for-using-greenluma-reborn-).

"Please keep in mind. Like CreamAPI, GreenLuma Reborn **does not** work for every game."

Nothing you can do to fix it. Sorry.
