### ISSUE TITLE
Green Luma

### ISSUE THREAD

**Issue by Toonsie** [linkthehylian/GreenLuma-Reborn-App#5]
Hey man, just tried using it today post today's update and doesn't seem to be working. Any news that you'll be updating / fixing it and or know a solution? Thanks!

**Comment by linkthehylian** [comment]
I'm not the developer of GLR. Steam006 is. I don't handle GLR updates. This is just my own app for his injector. Seek his [thread](https://cs.rin.ru/forum/viewtopic.php?f=29&t=80797) for when he updates.
