### ISSUE TITLE
GLR is over

### ISSUE THREAD

**Issue by Adicek-jpg** [linkthehylian/GreenLuma-Reborn-App#8]
On April 28th 2020, all GLR or GL2020 versions got server patched without any Steam update. Author pushed 1.0.8 in less than one hour claiming it works but people that are realistic know that this is the end of this tool. A tragedy, but it was only a matter of time.

cs.rin.ru is also offline, so now he has time to maybe try to make it work without forum pressure, however at this point consider the tool dead.

**Comment by linkthehylian** [comment]
I don't know what kinda realization you had there but GL2020 works just fine. I have a friend playing Devil May Cry 5 off of my library right now using an older version of GL2020 too.

I'm aware rin's also offline and I don't know when it'll be back up. Steam006 constantly pushes out updates for his tool so I wouldn't deem it "over" just yet. The tool seems to be a hit or miss for a lot of users and that's something I can't fix.

**Comment by linkthehylian** [comment]
@Adicek-jpg 
Are you willing to give a proper reply or are you just gonna thumbs down my post because you personally don't agree with it?

**Comment by Adicek-jpg** [comment]
Yes, the proper reply is this. GLR  and GL2020 with DLLInjector do not work, I had to grab a 2017 one.

And don't bullshit me about how I don't know how to use it, I have been using it for days. It stopped working suddenly for multiple people. and the new crap version that was pulled out of thin air 20 minutes after it stopped working does not work either. I spent too much time trying to configure it in 100 ways and then I found a random 2017 version and my PC and it worked like a charm on very first try.

**Comment by linkthehylian** [comment]
I'm glad to hear that an older version works for you. But I'm not sorry to say that the latest version still works fine.

Here's a screenshot. Each highlighted game is a game from another shared library.
![screenshot](https://user-images.githubusercontent.com/20933012/80786445-ab410b80-8b51-11ea-9989-fc899397e20d.png)

And you seemed to completely missed what I'd said previously;

> The tool seems to be a hit or miss for a lot of users and that's something I can't fix.

This repository is for my app for GL2020. Not the tool itself. I'm not the one you wanna complain to. Good luck in your endeavors.

**Comment by Adicek-jpg** [comment]
No it does not work.

**Comment by linkthehylian** [comment]
Also 100% sure you can't speak for everyone based on your own personal preference. 1.0.8 works fine. I'm sorry to hear that you're having issues. Maybe when the forum is online again you can ask Steam006 yourself. 😄
