### ISSUE TITLE
GLR crashing game

### ISSUE THREAD

**Issue by Asshubs** [linkthehylian/GreenLuma-Reborn-App#9]
Well it is crashing monster hunter world for me at the moment ? anyone got a fix?

**Comment by linkthehylian** [comment]
> Please **do not** ask me about anything related to GL2020. I'm not the developer of it. Steam006 is. This is just a small app I made to add app IDs with. Report any issues you have [here](https://cs.rin.ru/forum/viewtopic.php?f=29&t=103709). Visit the [FaQ](https://github.com/linkthehylian/GreenLuma-Reborn-App/wiki/FaQ) if you have any questions about GL2020 itself.
